# Use an official Node.js runtime as a parent image
FROM node:20.14.0

# Set the working directory
WORKDIR /

# Copy package.json and yarn.lock
COPY package*.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose port
EXPOSE 3000

# Start the backend service
CMD ["yarn", "run" , "dev"]